# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Shun' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shun

  target 'ShunTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShunUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Firebase'
  pod 'FirebaseFirestore'
  pod 'SDWebImage'
end
